In [1]:
%matplotlib inline
import itertools

import matplotlib as mpl
import matplotlib.pyplot as plt
import pennylane as qml
from pennylane import numpy as np
from pennylane.templates import BasisEmbedding, AmplitudeEmbedding, AngleEmbedding
from pennylane import QubitStateVector

n_qubits = 5
dev = qml.device('default.qubit', wires=n_qubits)

qml.enable_tape()
mpl.rcParams['figure.dpi'] = 100

# Quantum embedding (Квантовое представление)
- Что такое признаки (features)?
- Quantum feature map
- Основные типы представления

Quantum embedding -- это представление классических данных в виде параметров квантовой схемы-генератора. Состояние на выходе генератора зависит от заданных классических данных.

См. https://arxiv.org/pdf/2001.03622.pdf

Если рассматривать процесс гибридных вычислений в общем, то его можно описать такой схемой:

<img src="https://quantum-science.systems/wp-content/uploads/2019/12/Hybrid-Algorithm.jpg">

## Что такое признаки?
Признаки (features) -- это числовое представление особенностей объекта. То есть объекту сопоставляется некоторый числовой вектор, который отражает его уникальность. Например, если у нас есть кубы и шары двух разных цветов (синего и красного), то мы можем описать их с помощью двухмерного вектора признаков, если проведем сопоставление $\{0: "шар", 1: "куб"\}$, $\{0: "синий", 1: "красный"\}$. Красный шар будет иметь вектор признаков $\{0, 1\}$.

Помимо дискретных, могут быть непрерывные признаки, например угол поворота или координаты.

Раньше признаки разрабатывали вручную, сейчас зачастую они генерируются с помощью глубоких нейронных сетей.

## Quantum feature map
Quantum feature map -- это преобразование, действующее из пространства классических в пространство квантовых признаков.

## Основные типы представления
### Basis embedding
Классические данные -- битовые строки. Идет сопоставление между битовой строкой и базисным квантовым состоянием вида $"01010"\to |01010\rangle$. Для этого строится кодирующая квантовая схема, переводящая исходное состояние $|0\rangle$ в состояние, соответствующее битовой строке, которая, если $i$-й бит равен 1, действует на $i$-й кубит с помощью операторов $X_i$, переводя его в состояние $|1\rangle$. Если на вход подается набор битовых строк $\{x_1,\dots,x_M\}$, то создается суперпозиционное состояние вида

$$ |X\rangle = \frac{1}{\sqrt{M}}\sum_{m=1}^{M} |x_m\rangle. $$

Таким образом, все дальнейшие квантовые операции проводятся над набором данных параллельно. Для представления $M$ битовых строк размерности $N$ необходимо как минимум $n=N$ кубитов.

Представление отдельной битовой строки

In [2]:
@qml.qnode(dev)
def coding_node(bits, n_qubits=5):
    BasisEmbedding(bits, wires=range(n_qubits))
    return qml.probs(wires=range(n_qubits))

coding_node([0, 1, 1, 0, 0])
print(coding_node.draw())

 0: ─────╭┤ Probs 
 1: ──X──├┤ Probs 
 2: ──X──├┤ Probs 
 3: ─────├┤ Probs 
 4: ─────╰┤ Probs 



Представление массива битовых строк. Для их представления необходим препроцессинг -- преобразование битовых строк в коэффициенты при базисных состояниях. Если базисное состояние соответствует строке, то она включается в состояние с амплитудой $1/\sqrt{M}$, иначе не включается.

При таком способе представления удобно использовать класс **QubitStateVector**, который принимает на вход амплитуды базисных состояний и генерирует на выходе состояние с заданными амплитудами.

In [3]:
@qml.qnode(dev)
def coding_node(bits_data, n_qubits=5):
    QubitStateVector(bits_data, wires=range(n_qubits))
    return qml.probs(wires=range(n_qubits))


def preprocess_data(bits_data):
    str_data = [str(b) for b in bits_data]
    basis = [str(np.tensor(i)) for i in itertools.product([0, 1], repeat=len(bits_data[0]))]
    weights = []
    for b in basis:
        weights.append(int(b in str_data) / np.sqrt(len(bits_data) - 1))
    return np.array(weights)

Создадим набор случайных битовых строк и преобразуем его в амплитуды

In [4]:
N = n_qubits
M = 10
initial_data = [np.random.randint(2, size=5) for i in range(M)]
initial_data = list(filter(lambda b: (int(sum(b)) < N) & (int(sum(b)) > 0), initial_data))
basis_data = preprocess_data(initial_data)
[str(b) for b in initial_data]

['[1 1 0 1 1]',
 '[0 1 1 1 0]',
 '[0 0 0 0 1]',
 '[0 1 1 1 1]',
 '[0 1 1 0 1]',
 '[1 0 0 0 1]',
 '[1 1 0 0 0]',
 '[0 1 1 0 1]',
 '[1 1 0 1 1]']

In [5]:
print(basis_data)

[0.         0.35355339 0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.35355339 0.35355339 0.35355339 0.         0.35355339
 0.         0.         0.         0.         0.         0.
 0.35355339 0.         0.         0.35355339 0.         0.
 0.         0.        ]


Посмотрим на сгенерированную схему

In [6]:
coding_node(basis_data / np.sqrt(np.sum(basis_data ** 2)))
print(coding_node.draw())

 0: ──╭QubitStateVector(M0)──╭┤ Probs 
 1: ──├QubitStateVector(M0)──├┤ Probs 
 2: ──├QubitStateVector(M0)──├┤ Probs 
 3: ──├QubitStateVector(M0)──├┤ Probs 
 4: ──╰QubitStateVector(M0)──╰┤ Probs 
M0 =
[0.         0.37796447 0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.37796447 0.37796447 0.37796447 0.         0.37796447
 0.         0.         0.         0.         0.         0.
 0.37796447 0.         0.         0.37796447 0.         0.
 0.         0.        ]



### Amplitude embedding
Классические данные -- набор векторов ($x_m\in\mathbb{R}^N$) с целыми или действительными числами. Для представления данных в квантовом виде их выстраивают в одномерный массив $\{x_{m,n}:m=1,\dots,M,n=1,\dots,N\}\to\{x_k:k=m + n=1,\dots,M\cdot N\}$. Массив нормируют на единицу и передают в качестве параметров в квантовую схему, состояние на выходе которой имеет вид:

$$ |X\rangle = \sum_{k=1}^{M\cdot N} x_k|k\rangle $$

Здесь $|k\rangle$ -- базисное состояние в вычислительном базисе. Для представления $M$ векторов размерности $N$ необходимо как минимум $n=\log_2{(MN)}$ кубитов. Если $MN\neq 2^n,n\in\mathbb{N}$, то исходные данные дополняются "неинформативными" константами, например нулями.

В **pennylane** для представления данных в амплитуды есть класс **AmplitudeEmbedding**. Сгенерируем случайные векторные данные. У нас есть 5 кубитов, поэтому $NM\leq 32$.

In [7]:
N = 4
M = 2 ** n_qubits // N
initial_data = [np.random.random_sample((N,)) for i in range(M)]
initial_data

[tensor([0.34923379, 0.10502114, 0.81841924, 0.88882221], requires_grad=True),
 tensor([0.15134612, 0.60742549, 0.15589015, 0.14904247], requires_grad=True),
 tensor([0.88675773, 0.33966529, 0.96404674, 0.20785152], requires_grad=True),
 tensor([0.69349711, 0.17870541, 0.47984352, 0.19774387], requires_grad=True),
 tensor([0.01409409, 0.17059605, 0.6874051 , 0.72108027], requires_grad=True),
 tensor([0.9484897 , 0.16578856, 0.2167648 , 0.83723223], requires_grad=True),
 tensor([0.85714106, 0.08962102, 0.36625976, 0.77715817], requires_grad=True),
 tensor([0.25587442, 0.35639624, 0.43142301, 0.87257302], requires_grad=True)]

In [8]:
@qml.qnode(dev)
def coding_node(data, n_qubits=5):
    AmplitudeEmbedding(features=data, wires=range(n_qubits), normalize=True)
    return qml.probs(wires=range(n_qubits))

In [9]:
amplitude_data = np.concatenate(initial_data)
coding_node(amplitude_data)
print(coding_node.draw())

 0: ──╭QubitStateVector(M0)──╭┤ Probs 
 1: ──├QubitStateVector(M0)──├┤ Probs 
 2: ──├QubitStateVector(M0)──├┤ Probs 
 3: ──├QubitStateVector(M0)──├┤ Probs 
 4: ──╰QubitStateVector(M0)──╰┤ Probs 
M0 =
[0.11040755 0.03320162 0.25873687 0.28099423 0.0478469  0.19203284
 0.04928346 0.04711862 0.28034156 0.10738254 0.30477588 0.06571064
 0.21924372 0.05649633 0.1516988  0.06251519 0.00445574 0.05393261
 0.21731777 0.22796392 0.29985764 0.05241276 0.06852851 0.26468446
 0.27097848 0.02833299 0.11579017 0.24569251 0.08089271 0.1126719
 0.13639103 0.27585717]



### Angle embedding
Еще один "простой" тип представления. Классические данные -- набор чисел $X=\{x_1,\dots,x_M\}\in\mathbb{R}^M$, и каждое число сопоставляется повороту кубита вокруг одной из трех осей. Например, при повороте вокруг оси $x$, состояние на выходе кодирующей схемы имеет вид:

$$ |X\rangle = \prod_{k=1}^M r_x(x_k)|0_k\rangle$$
Где $|0_k\rangle$ -- основное состояние $k$-го кубита. Для внедрения $M$ числе необходимо как минимум $n=M$ кубитов.

Для этого представления в **pennylane** есть класс **AngleEmbedding**. Создадим набор случайных чисел размерности $M=5$

In [10]:
M = n_qubits
initial_data = np.random.random_sample((M,))
initial_data

tensor([0.23251476, 0.5941253 , 0.31757757, 0.21611173, 0.2598239 ], requires_grad=True)

In [11]:
@qml.qnode(dev)
def coding_node(data, n_qubits=5):
    AngleEmbedding(features=data, wires=range(n_qubits))
    return qml.probs(wires=range(n_qubits))

In [12]:
coding_node(initial_data)
print(coding_node.draw())

 0: ──RX(0.233)──╭┤ Probs 
 1: ──RX(0.594)──├┤ Probs 
 2: ──RX(0.318)──├┤ Probs 
 3: ──RX(0.216)──├┤ Probs 
 4: ──RX(0.26)───╰┤ Probs 

